name: Build and Publish Spoolman Image

on:
  workflow_dispatch: # manually triggered
  schedule:
    - cron: '0 3 * * 6' # optional: build each saturday at 03:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Spoolman fork
        uses: actions/checkout@v4
        with:
          repository: chof747/spoolman
          ref: master

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/spoolman
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
